# config/config/config.yml
doctrine:
    dbal:
        default_connection: default
        charset: utf8mb4
        connections:
            default:
                driver: pdo_sqlite
                memory: true
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci