controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path:       /
    controller: App\Controller\MainPageController::renderMainPage

new_team:
    path:       /newTeam
    controller: App\Controller\TeamController::renderNewTeam

delete_team:
    path:       /{id}/deleteTeam
    controller: App\Controller\TeamController::renderDeleteTeam

increase_shot:
    path: /{id}/increase
    controller: App\Controller\TeamController::increaseShotsOfTeam

update_teams:
    path: /update/teams
    controller: App\Controller\TeamController::getUpdatedTeams

chart_view:
    path: /chartView
    controller: App\Controller\ChartController::chartShow

bar_view:
    path: /barView
    controller: App\Controller\BarPageController::renderBarPage
